"""add new tables for profile feature

Revision ID: 08e1c9bf3141
Revises: 6c1e0ffef66f
Create Date: 2025-09-27 12:18:42.444014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e1c9bf3141'
down_revision: Union[str, Sequence[str], None] = '6c1e0ffef66f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
